package ir.amirhesambandegan.easify_location

import android.location.Location
import android.os.Build

/**
 * Checks whether the current [Location] is mocked or spoofed by a mock location provider/app.
 *
 * On Android 12 (API level 31, [Build.VERSION_CODES.S]) and above, this relies on [Location.isMock].
 * On earlier versions, it falls back to the deprecated [Location.isFromMockProvider].
 *
 * @receiver The [Location] instance to check for mock/spoofed status.
 * @return `true` if the location was generated by a mock provider, `false` otherwise.
 */
fun Location.isMocked(): Boolean {
    return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
        this.isMock
    } else {
        @Suppress("DEPRECATION")
        this.isFromMockProvider
    }
}
